import './browse-widget.js';
import './content-blocks.js';
import './datetimepicker.js';
import './drag-n-drop.js';
import './dropzone.js';
import './editor.js';
import './form-utils.js';
import './imagelightbox.js';
import './jquery.form-submission-attributes.polyfill.js';
import './language-changer.js';
import './materialize.js';
import './messages.js';
import './popover.js';
import './quick_add_related_objects.js';
import './search.js';
import './side-nav.js';
import './slugify.js';
import './timesince.js';
import './tooltip.js';
import './tour.js';
import './select.js';
import handleMainMenu from './main-menu.js';

handleMainMenu();
