# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shuup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='Check this if this tax rule is active.', verbose_name='enabled')),
                ('country_codes_pattern', models.CharField(blank=True, max_length=300, verbose_name='country codes pattern')),
                ('region_codes_pattern', models.CharField(blank=True, max_length=500, verbose_name='region codes pattern')),
                ('postal_codes_pattern', models.TextField(blank=True, verbose_name='postal codes pattern')),
                ('_postal_codes_min', models.CharField(blank=True, max_length=100, null=True)),
                ('_postal_codes_max', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Rules with same priority define added taxes (e.g. US taxes) and rules with different priority define compound taxes (e.g. Canada Quebec PST case)', verbose_name='priority')),
                ('override_group', models.IntegerField(default=0, help_text='If several rules match, only the rules with the highest override group number will be effective.  This can be used, for example, to implement tax exemption by adding a rule with very high override group that sets a zero tax.', verbose_name='override group number')),
                ('customer_tax_groups', models.ManyToManyField(blank=True, help_text='The customer tax groups for which this tax rule is limited.', to='shuup.CustomerTaxGroup', verbose_name='customer tax groups')),
                ('tax', models.ForeignKey(help_text='The tax to apply when this rule is applied.', on_delete=django.db.models.deletion.PROTECT, to='shuup.Tax', verbose_name='tax')),
                ('tax_classes', models.ManyToManyField(help_text='Tax classes of the items to be taxed', to='shuup.TaxClass', verbose_name='tax classes')),
            ],
        ),
    ]
