# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_tax', '0001_squashed_0003_alter_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrule',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='Enable this if this tax rule is active.', verbose_name='enabled'),
        ),
    ]
