# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-25 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shuup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierWithCheckoutPhase',
            fields=[
                ('customcarrier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shuup.CustomCarrier')),
            ],
            options={
                'abstract': False,
            },
            bases=('shuup.customcarrier',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExpensiveSwedenBehaviorComponent',
            fields=[
                ('servicebehaviorcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shuup.ServiceBehaviorComponent')),
            ],
            options={
                'abstract': False,
            },
            bases=('shuup.servicebehaviorcomponent',),
        ),
        migrations.CreateModel(
            name='PaymentWithCheckoutPhase',
            fields=[
                ('custompaymentprocessor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shuup.CustomPaymentProcessor')),
            ],
            options={
                'abstract': False,
            },
            bases=('shuup.custompaymentprocessor',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PseudoPaymentProcessor',
            fields=[
                ('paymentprocessor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shuup.PaymentProcessor')),
                ('bg_color', models.CharField(blank=True, default='white', max_length=20, verbose_name='Payment Page Background Color')),
                ('fg_color', models.CharField(blank=True, default='black', max_length=20, verbose_name='Payment Page Text Color')),
            ],
            options={
                'abstract': False,
            },
            bases=('shuup.paymentprocessor',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
