# Generated by Django 2.2.15 on 2020-08-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_testing', '0005_supplierprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ultrafilter',
            options={'base_manager_name': 'objects'},
        ),
    ]
