# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-28 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_customer_group_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cgpprice',
            options={'permissions': (('view_cgpprice', 'Can view customer group pricing'),), 'verbose_name': 'product price', 'verbose_name_plural': 'product prices'},
        ),
    ]
