# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-25 13:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import shuup.core.fields
import shuup.utils.properties


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_customer_group_pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CgpDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount_value', shuup.core.fields.MoneyValueField(decimal_places=9, max_digits=36, verbose_name='discount amount')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuup.ContactGroup', verbose_name='contact group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shuup.Product', verbose_name='product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuup.Shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'product discount',
                'verbose_name_plural': 'product discounts',
                'abstract': False,
            },
            bases=(shuup.utils.properties.MoneyPropped, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='cgpdiscount',
            unique_together=set([('product', 'shop', 'group')]),
        ),
    ]
