# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0057_remove_product_stock_behavior'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Select supplier for this discount.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_discounts', to='shuup.Supplier', verbose_name='supplier'),
        ),
    ]
