# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-30 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_help-text-improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityexception',
            name='end_datetime',
            field=models.DateTimeField(help_text='Set to restrict the availability exception to be available only until a certain date and time.', verbose_name='end until'),
        ),
        migrations.AlterField(
            model_name='availabilityexception',
            name='start_datetime',
            field=models.DateTimeField(help_text='Set to restrict the availability exception to be available only after a certain date and time.', verbose_name='start since'),
        ),
    ]
