# Generated by Django 2.2.18 on 2021-07-28 19:59
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuup", "0094_product_catalog"),
        ("discounts", "0004_improve_availabilityexception_descriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_discounts",
                to="shuup.Shop",
                verbose_name="shop",
            ),
        ),
        migrations.AddField(
            model_name="happyhour",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shuup.Shop",
                verbose_name="shop",
            ),
        ),
    ]
