# Generated by Django 2.2.18 on 2021-08-01 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_delete_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProductCatalogDiscountsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounts', models.ManyToManyField(blank=True, related_name='shop_products_link', to='discounts.Discount')),
                ('shop_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discounts_link', to='shuup.ShopProduct')),
            ],
        ),
    ]
