# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shuup', '0045_disable_default_marketing_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicFilterSettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('layout', models.SmallIntegerField(choices=[(1, 'Vertical'), (2, 'Horizontal')], default=1, verbose_name='Layout')),
                ('dispay_number_of_products', models.BooleanField(default=True, verbose_name='Display number of products')),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shuup.Shop')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousels',
            },
        ),
    ]
