# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_filter', '0003_auto_20180709_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesfiltermodel',
            name='enabled',
        ),
        migrations.AlterField(
            model_name='categoriesfiltermodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shuup.Category'),
        ),
    ]
