# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0045_disable_default_marketing_permission'),
        ('product_filter', '0004_auto_20180710_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesfiltermodel',
            name='category',
        ),
        migrations.AddField(
            model_name='categoriesfiltermodel',
            name='category',
            field=models.ManyToManyField(default=1, to='shuup.Category'),
        ),
    ]
