# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-14 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_filter', '0005_auto_20180710_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesFilterModel',
            new_name='CategoriesFilterSettingsModel',
        ),
    ]
