# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-14 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0045_disable_default_marketing_permission'),
        ('product_filter', '0007_attributesfiltersettingsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributesfiltersettingsmodel',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shuup.Shop'),
        ),
    ]
