# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_filter', '0008_attributesfiltersettingsmodel_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesfiltersettingsmodel',
            name='filter_type',
            field=models.SmallIntegerField(choices=[(1, 'Checkbox'), (2, 'Droupdown'), (3, 'Range')], default=1, verbose_name='Filter type'),
        ),
        migrations.AlterField(
            model_name='attributesfiltersettingsmodel',
            name='filter_type',
            field=models.SmallIntegerField(choices=[(1, 'Checkbox'), (2, 'Droupdown'), (3, 'Range')], default=1, verbose_name='Filter type'),
        ),
    ]
