# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0045_disable_default_marketing_permission'),
        ('product_filter', '0010_auto_20180730_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAttributesFilterSettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=60)),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('filter_type', models.SmallIntegerField(choices=[(1, 'Checkbox'), (2, 'Droupdown'), (3, 'Range')], default=1, verbose_name='Filter type')),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shuup.Shop')),
            ],
            options={
                'verbose_name_plural': 'Basic filter attributes settings',
                'verbose_name': 'Basic filter attribute setting',
            },
        ),
    ]
