# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-17 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_filter', '0011_basicattributesfiltersettingsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributesfiltersettingsmodel',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='basicattributesfiltersettingsmodel',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='basicfiltersettingsmodel',
            name='dispay_number_of_products',
        ),
    ]
