# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-03 14:59
from __future__ import unicode_literals

from django.db import migrations
import shuup.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0003_add_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='arrows_color',
            field=shuup.core.fields.HexColorField(blank=True, help_text='Set the custom color for the arrows.', max_length=9, null=True, verbose_name='Arrows color'),
        ),
        migrations.AddField(
            model_name='slide',
            name='active_dot_color',
            field=shuup.core.fields.HexColorField(blank=True, help_text='Customize the dot color when slide is active.', max_length=9, null=True, verbose_name='Active dot color'),
        ),
        migrations.AddField(
            model_name='slide',
            name='inactive_dot_color',
            field=shuup.core.fields.HexColorField(blank=True, help_text='Customize the dot border color when slide is not active.', max_length=9, null=True, verbose_name='Inactive dot border color'),
        ),
    ]
