# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-08 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0004_custom_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidetranslation',
            name='external_link',
            field=models.CharField(blank=True, help_text='Set the external site that should be shown when this slide is clicked, if any.', max_length=800, null=True, verbose_name='external link'),
        ),
    ]
