# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-29 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0006_improve_carousel_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Set the date and time, starting from which this slide should be visible in the carousel. This is useful to advertise sales campaigns or other time-sensitive marketing.', null=True, verbose_name='available since'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='available_to',
            field=models.DateTimeField(blank=True, help_text='Set the date and time, until which this slide should be visible in the carousel. This is useful to advertise sales campaigns or other time-sensitive marketing.', null=True, verbose_name='available until'),
        ),
    ]
