# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-22 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0029_multishop_and_more'),
        ('shuup_xtheme', '0002_md_to_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_settings', to='shuup.Shop'),
        ),
    ]
