# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-14 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_xtheme', '0004_convert_shop_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='theme_identifier',
            field=models.CharField(db_index=True, max_length=64, verbose_name='theme identifier'),
        ),
    ]
