# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-01 16:35
from __future__ import unicode_literals

from django.db import migrations


def add_shop_to_pages(apps, schema_editor):
    Shop = apps.get_model("shuup", "Shop")
    Page = apps.get_model("shuup_simple_cms", "Page")
    Page.objects.all().update(shop=Shop.objects.first())


class Migration(migrations.Migration):
    dependencies = [
        ('shuup_simple_cms', '0004_add_shop')
    ]

    operations = [
        migrations.RunPython(add_shop_to_pages, migrations.RunPython.noop)
    ]
