# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-27 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_simple_cms', '0009_remove_page_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='render_title',
            field=models.BooleanField(default=True, help_text='Check this if this page should have a visible title', verbose_name='render title'),
        ),
    ]
