# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 20:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0058_make_product_type_nullable'),
        ('shuup_simple_cms', '0012_available_from_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shuup.Supplier', verbose_name='supplier'),
        ),
    ]
