# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 23:00
from __future__ import unicode_literals

from django.db import migrations

import shuup.utils.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0009_update_tax_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='carrier',
            managers=(shuup.utils.migrations.get_managers_for_migration()),
        ),
        migrations.AlterModelManagers(
            name='customcarrier',
            managers=(shuup.utils.migrations.get_managers_for_migration()),
        ),
        migrations.AlterModelManagers(
            name='custompaymentprocessor',
            managers=(shuup.utils.migrations.get_managers_for_migration()),
        ),
        migrations.AlterModelManagers(
            name='paymentprocessor',
            managers=(shuup.utils.migrations.get_managers_for_migration()),
        ),
        migrations.AlterModelManagers(
            name='serviceprovider',
            managers=(shuup.utils.migrations.get_managers_for_migration()),
        ),
    ]
