# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-05 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0010_update_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
