# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-05 21:26
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import shuup.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0017_ensure_currencies_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=enumfields.fields.EnumIntegerField(db_index=True, default=1, enum=shuup.core.models.CategoryStatus),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='visibility',
            field=enumfields.fields.EnumIntegerField(db_index=True, default=3, enum=shuup.core.models.ShopProductVisibility),
        ),
    ]
