# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0025_product_variation_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='immutableaddress',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='immutableaddress',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='mutableaddress',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='mutableaddress',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, blank=True),
        ),
    ]
