# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-17 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0025_product_variation_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariationvariable',
            options={'ordering': ('ordering',), 'verbose_name': 'variation variable', 'verbose_name_plural': 'variation variables'},
        ),
        migrations.AlterModelOptions(
            name='productvariationvariablevalue',
            options={'ordering': ('ordering',), 'verbose_name': 'variation value', 'verbose_name_plural': 'variation values'},
        ),
    ]
