# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-28 02:24
from __future__ import unicode_literals

from django.db import migrations
import shuup.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0026_address_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='identifier',
            field=shuup.core.fields.InternalIdentifierField(blank=True, editable=False, max_length=96, null=True, unique=True),
        ),
    ]
