# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-29 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0027_modify_shop_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('tree_id', 'lft'), 'permissions': (('view_category', 'Can view categories'),), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='companycontact',
            options={'permissions': (('view_companycontact', 'Can view company contacts'),), 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': (('view_contact', 'Can view any contacts'),), 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='contactgroup',
            options={'permissions': (('view_contactgroup', 'Can view contact groups'),), 'verbose_name': 'contact group', 'verbose_name_plural': 'contact groups'},
        ),
        migrations.AlterModelOptions(
            name='customertaxgroup',
            options={'permissions': (('view_customertaxgroup', 'Can view customer tax groups'),), 'verbose_name': 'customer tax group', 'verbose_name_plural': 'customer tax groups'},
        ),
        migrations.AlterModelOptions(
            name='immutableaddress',
            options={'permissions': (('view_address', 'Can view addresses'),), 'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'permissions': (('view_manufacturer', 'Can view manufacturers'),), 'verbose_name': 'manufacturer', 'verbose_name_plural': 'manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='mutableaddress',
            options={'permissions': (('view_address', 'Can view addresses'),), 'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'permissions': (('view_order', 'Can view orders'),), 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': (('view_payment', 'Can view payments'),), 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'permissions': (('view_paymentmethod', 'Can view payment methods'),), 'verbose_name': 'payment method', 'verbose_name_plural': 'payment methods'},
        ),
        migrations.AlterModelOptions(
            name='personcontact',
            options={'permissions': (('view_personcontact', 'Can view person contacts'),), 'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'permissions': (('view_product', 'Can view products'),), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ['ordering'], 'permissions': (('view_productmedia', 'Can view media'),), 'verbose_name': 'product attachment', 'verbose_name_plural': 'product attachments'},
        ),
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'permissions': (('view_serviceprovider', 'Can view any service providers'),), 'verbose_name': 'service provider', 'verbose_name_plural': 'service providers'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'permissions': (('view_shipment', 'Can view shipments'),), 'verbose_name': 'shipment', 'verbose_name_plural': 'shipments'},
        ),
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'permissions': (('view_shippingmethod', 'Can view shipping methods'),), 'verbose_name': 'shipping method', 'verbose_name_plural': 'shipping methods'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': (('view_shop', 'Can view shops'),), 'verbose_name': 'shop', 'verbose_name_plural': 'shops'},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'permissions': (('view_shopproduct', 'Can view shop products'),)},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'permissions': (('view_supplier', 'Can view suppliers'),), 'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'permissions': (('view_tax', 'Can view taxes'),), 'verbose_name': 'tax', 'verbose_name_plural': 'taxes'},
        ),
        migrations.AlterModelOptions(
            name='taxclass',
            options={'permissions': (('view_taxclass', 'Can view tax classes'),), 'verbose_name': 'tax class', 'verbose_name_plural': 'tax classes'},
        ),
    ]
