# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-30 21:52
from __future__ import unicode_literals

from django.db import migrations


def synchronize_staff_members(apps, schema_editor):
    shop = apps.get_model("shuup", "Shop").objects.first()
    if shop:
        user_model = apps.get_model("auth", "User")
        for user in user_model.objects.filter(is_staff=True):
            shop.staff_members.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0028_add_view_permissions'),
    ]

    operations = [
        migrations.RunPython(synchronize_staff_members, migrations.RunPython.noop)
    ]
