# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-13 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0031_synchronize_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopobjectpermission',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='shopobjectpermission',
            name='shop',
        ),
        migrations.DeleteModel(
            name='ShopObjectPermission',
        ),
    ]
