# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0032_shop_product_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='modified on'),
        )
    ]
