# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-27 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0033_order_modified_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': (('view_shop', 'Can view shops'),), 'verbose_name': 'shop', 'verbose_name_plural': 'shops'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='shuup.Shop'),
        ),
    ]
