# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-22 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0036_shop_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        )
    ]
