# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0037_modified_on_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
