# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-12 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0040_order_created_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='shops',
            field=models.ManyToManyField(blank=True, to='shuup.Shop', verbose_name='shops'),
        ),
    ]
