# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-29 23:46
from __future__ import unicode_literals

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('shuup', '0048_contactgroup_pricedisplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_logos', to=settings.FILER_IMAGE_MODEL, verbose_name='logo'),
        ),
    ]
