# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0055_order_line_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_behavior',
        ),
    ]
