# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0056_attributes_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_behavior',
        ),
    ]
