# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 23:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0057_remove_product_stock_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(help_text='Select a product type for your product. These allow you to configure custom attributes to help with classification and analysis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shuup.ProductType', verbose_name='product type'),
        ),
    ]
