# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0059_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
