# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-09 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0061_order_line_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter a URL Slug for your supplier. This is what your supplier page URL will be. A default will be created using the supplier name.', max_length=255, null=True, verbose_name='slug'),
        ),
    ]
