# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-18 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0062_add-supplier-slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='staff_members',
            field=models.ManyToManyField(blank=True, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='staff members'),
        ),
    ]
