# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-27 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('shuup', '0065_add_db_indexes_to_prod_cat_and_supplier_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='picture',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Contact picture. Can be used alongside contact profile, reviews and messages for example.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picture', to=settings.FILER_IMAGE_MODEL, verbose_name='picture'),
        ),
    ]
