# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0066_contact-picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, help_text='The product suppliers name. Suppliers can be used manage the inventory of stocked products.', max_length=128, verbose_name='name'),
        ),
    ]
