# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-14 06:32
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0067_supplier_name_max_length_to_128'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, help_text='The timezone in which the shop resides. This can be used to target the delivery of promotional materials at a particular time.', null=True, verbose_name='time zone'),
        ),
    ]
