# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-06 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shuup', '0070_dynamic_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafolder',
            name='root_folder_for',
            field=models.ManyToManyField(help_text='Select which users will have this folder as their root folder.', related_name='root_media_folder', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='user_access',
            field=models.ManyToManyField(help_text='Select which users has access to this folder.', related_name='media_folders', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
