# Generated by Django 2.2.15 on 2020-10-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0073_add_owner_to_media_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=True, help_text='Indicates whether this supplier is currently approved for work.', verbose_name='Approved')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuup.Shop', related_name='supplier_shops')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuup.Supplier', related_name='supplier_shops')),
            ],
            options={
                'unique_together': {('supplier', 'shop')},
            },
        ),
    ]
