# Generated by Django 2.2.15 on 2020-10-22 13:53

from django.db import migrations


def create_supplier_shops(apps, schema_editor):
    Supplier = apps.get_model("shuup", "Supplier")
    SupplierShop = apps.get_model("shuup", "SupplierShop")

    for supplier in Supplier.objects.all():
        for shop in supplier.shops.all():
            SupplierShop.objects.create(
                supplier=supplier,
                shop=shop,
                is_approved=supplier.is_approved
            )


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0074_supplier_shops'),
    ]

    operations = [
        migrations.RunPython(create_supplier_shops, migrations.RunPython.noop)
    ]
