# Generated by Django 2.2.15 on 2020-10-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0075_move_supplier_shops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='shops',
        ),
        migrations.AddField(
            model_name='supplier',
            name='shops',
            field=models.ManyToManyField(blank=True, help_text='You can select which particular shops fronts the supplier should be available in.', related_name='suppliers', through='shuup.SupplierShop', to='shuup.Shop', verbose_name='shops'),
        ),
    ]
