# Generated by Django 2.2.15 on 2021-01-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0079_longer_log_entry_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='tax_number',
            field=models.CharField(blank=True, help_text='e.g. EIN in US or VAT code in Europe', max_length=64, verbose_name='tax number'),
        ),
        migrations.AlterField(
            model_name='countrylimitbehaviorcomponent',
            name='available_in_european_countries',
            field=models.BooleanField(default=False, verbose_name='available in european union'),
        ),
        migrations.AlterField(
            model_name='countrylimitbehaviorcomponent',
            name='unavailable_in_european_countries',
            field=models.BooleanField(default=False, verbose_name='unavailable in european union'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='tax number'),
        ),
    ]
