# Generated by Django 2.2.17 on 2021-02-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0082_add_name_to_shop_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetranslation',
            name='name',
            field=models.CharField(help_text='The attribute name. Product attributes can be used to list the various features of a product and can be shown on the product detail page. The product attributes for a product are determined by the product type and can be set on the product editor page.', max_length=256, verbose_name='name'),
        ),
    ]
