# Generated by Django 2.2.17 on 2021-03-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0084_tracking_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='sku',
            field=models.CharField(blank=True, max_length=128, verbose_name='line SKU'),
        ),
    ]
