# Generated by Django 2.2.18 on 2021-04-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0085_longer_order_line_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='internal_type',
            field=models.IntegerField(choices=[(0, 'Normal product')], default=0),
        ),
    ]
