# Generated by Django 2.2.19 on 2021-05-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0086_attribute_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='max_choices',
            field=models.PositiveIntegerField(default=1, help_text='Maximum amount of choices that user can choose from existing options. This field has affect only for choices type.', verbose_name='Maximum amount of choices'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='min_choices',
            field=models.PositiveIntegerField(default=0, help_text='Minimum amount of choices that user can choose from existing options. This field has affect only for choices type.', verbose_name='Minimum amount of choices'),
        ),
    ]
