# Generated by Django 2.2.24 on 2021-07-15 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shuup.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shuup', '0091_background_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='allowed_next_statuses',
            field=models.ManyToManyField(to='shuup.OrderStatus', verbose_name='allowed next statuses'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', shuup.core.fields.UnsavedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_status_history_created', to=settings.AUTH_USER_MODEL, verbose_name='creating user')),
            ],
        ),
    ]
