# Generated by Django 2.2.18 on 2021-07-26 16:15

import django.db.models.deletion
import parler.fields
from django.db import migrations, models

import shuup.core.fields
import shuup.utils.properties


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0092_order_status_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='public',
            field=models.BooleanField(blank=True, db_index=True, default=True, help_text='Enable this if you want this image be shown on the product page. Enabled by default.', verbose_name='public (shown on product page)'),
        ),
        migrations.AlterField(
            model_name='salesunittranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shuup.SalesUnit'),
        ),
        migrations.CreateModel(
            name='ProductCatalogPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', shuup.core.fields.MoneyValueField(decimal_places=9, editable=False, help_text='The indexed product price', max_digits=36, verbose_name='price')),
                ('discounted_price_value', shuup.core.fields.MoneyValueField(decimal_places=9, editable=False, help_text='The indexed discounted product price.', max_digits=36, null=True, verbose_name='discounted price')),
                ('is_available', models.BooleanField(db_index=True, default=False, editable=False, help_text='Whether the product is available for purchasing. This status is managed by the supplier module.', verbose_name='is available')),
                ('contact', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to='shuup.Contact')),
                ('contact_group', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to='shuup.ContactGroup')),
                ('product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to='shuup.Product')),
                ('shop', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to='shuup.Shop')),
                ('supplier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to='shuup.Supplier')),
            ],
            bases=(shuup.utils.properties.MoneyPropped, models.Model),
        ),
        migrations.AddIndex(
            model_name='productcatalogprice',
            index=models.Index(fields=['product', 'shop', 'supplier', 'is_available'], name='shuup_produ_product_fece4b_idx'),
        ),
        migrations.AddIndex(
            model_name='productcatalogprice',
            index=models.Index(fields=['product', 'shop', 'supplier', 'contact', 'is_available'], name='shuup_produ_product_14a284_idx'),
        ),
        migrations.AddIndex(
            model_name='productcatalogprice',
            index=models.Index(fields=['product', 'shop', 'supplier', 'contact_group', 'is_available'], name='shuup_produ_product_27434f_idx'),
        ),
        migrations.AddIndex(
            model_name='productcatalogprice',
            index=models.Index(fields=['product', 'shop', 'supplier', 'contact_group', 'contact', 'is_available'], name='shuup_produ_product_6b51a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcatalogprice',
            unique_together={('product', 'shop', 'supplier', 'contact_group', 'contact')},
        ),
    ]
