# Generated by Django 2.2.24 on 2021-08-06 18:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0095_reindex_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immutableaddress',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='The primary phone number for the address.', max_length=128, region=None, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='mutableaddress',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='The primary phone number for the address.', max_length=128, region=None, verbose_name='phone'),
        ),
    ]
