# Generated by Django 2.2.24 on 2021-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0098_change_productmedia_verbose_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesapalPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_reference', models.CharField(max_length=255)),
                ('pesapal_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_used', models.BooleanField(default=False)),
                ('pesapal_status', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.TextField()),
            ],
        ),
    ]
