# Generated by Django 2.2.24 on 2021-09-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0099_pesapalpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesapalpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
