# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_supplier', '0001_squashed_0003_stockcount_alert_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='shuup.Product', verbose_name='product'),
        ),
    ]
