# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-24 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shuup', '0044_add_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPRCookieCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('always_active', models.BooleanField(default=False, verbose_name='always active')),
                ('cookies', models.TextField(help_text='Comma separated list of cookies names, prefix or sufix that will be included in this category, e.g. _ga, mysession, user_c_', verbose_name='cookies used')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hdpr_cookie_categories', to='shuup.Shop')),
            ],
            options={
                'verbose_name_plural': 'gdpr cookie categories',
                'verbose_name': 'gdpr cookie category',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GDPRCookieCategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('how_is_used', models.TextField(blank=True, help_text='Describe the purpose of this category of cookies and how it is used.', verbose_name='how we use')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shuup_gdpr.GDPRCookieCategory')),
            ],
            options={
                'managed': True,
                'db_tablespace': '',
                'verbose_name': 'gdpr cookie category Translation',
                'db_table': 'shuup_gdpr_gdprcookiecategory_translation',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GDPRSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Define if the GDPR is active.', verbose_name='enabled')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_settings', to='shuup.Shop')),
            ],
            options={
                'verbose_name_plural': 'gdpr settings',
                'verbose_name': 'gdpr settings',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GDPRSettingsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('cookie_banner_content', models.TextField(blank=True, help_text='The text to be present to users in cookie pop-up warning.', verbose_name='cookie banner content')),
                ('cookie_privacy_excerpt', models.TextField(blank=True, help_text='The summary text to be present about cookie privacy.', verbose_name='cookie privacy excerpt')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shuup_gdpr.GDPRSettings')),
            ],
            options={
                'managed': True,
                'db_tablespace': '',
                'verbose_name': 'gdpr settings Translation',
                'db_table': 'shuup_gdpr_gdprsettings_translation',
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='gdprsettingstranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='gdprcookiecategorytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
