# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-19 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        ('shuup_simple_cms', '0007_gdpr'),
        ('shuup_gdpr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPRUserConsentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuup_simple_cms.Page')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reversion.Version')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gdprcookiecategory',
            options={'verbose_name': 'GDPR cookie category', 'verbose_name_plural': 'GDPR cookie categories'},
        ),
        migrations.AlterModelOptions(
            name='gdprcookiecategorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'GDPR cookie category Translation'},
        ),
        migrations.AlterModelOptions(
            name='gdprsettings',
            options={'verbose_name': 'GDPR settings', 'verbose_name_plural': 'GDPR settings'},
        ),
        migrations.AlterModelOptions(
            name='gdprsettingstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'GDPR settings Translation'},
        ),
        migrations.AlterModelOptions(
            name='gdpruserconsent',
            options={'verbose_name': 'GDPR user consent', 'verbose_name_plural': 'GDPR user consents'},
        ),
        migrations.AlterField(
            model_name='gdpruserconsent',
            name='documents',
            field=models.ManyToManyField(blank=True, editable=False, to='shuup_gdpr.GDPRUserConsentDocument', verbose_name='consent documents'),
        ),
    ]
