# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-21 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_simple_cms', '0008_page_show_child_timestamps'),
        ('shuup_gdpr', '0003_consent_documents_m2m_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdprsettings',
            name='consent_pages',
            field=models.ManyToManyField(help_text='Choose pages here which are being monitored for customer consent. If any of these pages change, the customer is being prompted for a new consent.', related_name='consent_settings', to='shuup_simple_cms.Page', verbose_name='consent pages'),
        ),
        migrations.AddField(
            model_name='gdprsettings',
            name='privacy_policy_page',
            field=models.ForeignKey(help_text='Choose your privacy policy page here. If this page changes, customers will be prompted for new consent.', null=True, on_delete=django.db.models.deletion.CASCADE, to='shuup_simple_cms.Page', verbose_name='privacy policy page'),
        ),
    ]
