# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_gdpr', '0004_controllable_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdprsettings',
            name='skip_consent_on_auth',
            field=models.BooleanField(default=False, help_text='Do not require consent on login when GDPR is activated.', verbose_name='skip consent on login'),
        ),
        migrations.AddField(
            model_name='gdprsettingstranslation',
            name='auth_consent_text',
            field=models.TextField(blank=True, help_text='Shown in login page between the form and the button. Optional but should be considered when the consent on login is disabled.', verbose_name='login consent text'),
        ),
    ]
