# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0010_update_managers'),
        ('campaigns', '0004_logmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogFilterCachedShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_shop_products', to='campaigns.CatalogFilter')),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_catalog_campaign_filters', to='shuup.ShopProduct')),
            ],
        ),
    ]
