# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-28 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_add_excluded_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketcampaign',
            options={'permissions': (('view_basketcampaign', 'Can view basket campaigns'),), 'verbose_name': 'basket campaign', 'verbose_name_plural': 'basket campaigns'},
        ),
        migrations.AlterModelOptions(
            name='basketcampaigntranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'basket campaign Translation'},
        ),
        migrations.AlterModelOptions(
            name='catalogcampaign',
            options={'permissions': (('view_catalogcampaign', 'Can view catalog campaigns'),), 'verbose_name': 'catalog campaign', 'verbose_name_plural': 'catalog campaigns'},
        ),
        migrations.AlterModelOptions(
            name='catalogcampaigntranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'catalog campaign Translation'},
        ),
    ]
