# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-14 21:09
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_freeproductline_quantity_to_quantityfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourCondition',
            fields=[
                ('contextcondition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.ContextCondition')),
                ('hour_start', models.TimeField()),
                ('hour_end', models.TimeField()),
                ('days', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
            options={
                'abstract': False,
            },
            bases=('campaigns.contextcondition',),
        ),
    ]
