# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 22:27
from __future__ import unicode_literals

import django
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_basket_campaign_undiscounted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourbasketcondition',
            name='days',
            field=models.CharField(
                verbose_name='days',
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^[\\d,]+\\Z' if django.VERSION < (1, 9) else '^\\d+(?:\\,\\d+)*\\Z', 32),
                        code='invalid',
                        message='Enter only digits separated by commas.'
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name='hourcondition',
            name='days',
            field=models.CharField(
                verbose_name='days',
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^[\\d,]+\\Z' if django.VERSION < (1, 9) else '^\\d+(?:\\,\\d+)*\\Z', 32),
                        code='invalid',
                        message='Enter only digits separated by commas.'
                    )
                ]
            ),
        ),
    ]
