# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 18:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_hourconfition_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourbasketcondition',
            name='days',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='days'),
        ),
        migrations.AlterField(
            model_name='hourcondition',
            name='days',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='days'),
        ),
    ]
