# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_set_coupon_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourbasketcondition',
            name='days',
            field=models.CharField(max_length=255, verbose_name='days'),
        ),
        migrations.AlterField(
            model_name='hourcondition',
            name='days',
            field=models.CharField(max_length=255, verbose_name='days'),
        ),
    ]
