# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_childrenproductcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketcampaign',
            name='active',
            field=models.BooleanField(default=False, help_text='Enable this if the campaign is currently active. Please also set a start and an end date.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='basketcampaign',
            name='basket_line_text',
            field=models.CharField(help_text='This text will be shown in a basket.', max_length=120, verbose_name='basket line text'),
        ),
        migrations.AlterField(
            model_name='basketcampaign',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='When set, this campaign will match only products from the selected supplier. Rules and Effects will also be restricted to include only the products of this supplier.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_campaigns', to='shuup.Supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='catalogcampaign',
            name='active',
            field=models.BooleanField(default=False, help_text='Enable this if the campaign is currently active. Please also set a start and an end date.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text="Set the absolute limit of usages for this coupon. If the limit is zero (0), coupon can't be used.", null=True, verbose_name='usage limit'),
        ),
        migrations.AlterField(
            model_name='discountfromproduct',
            name='per_line_discount',
            field=models.BooleanField(default=True, help_text='Disable this if you want to give discount for each matched product.', verbose_name='per line discount'),
        ),
    ]
