# Generated by Django 2.2.14 on 2020-07-23 08:48

import django.db.models.deletion
import parler.fields
from django.db import migrations, models

import shuup.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_help-text-improvements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='basketmaxtotalamountcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='basketmaxtotalproductamountcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='baskettotalamountcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='baskettotalproductamountcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='baskettotalundiscountedproductamountcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='catalogfilter',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='categoryfilter',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='categoryproductsbasketcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='childrenproductcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='contactbasketcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='contactcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='contactgroupbasketcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='contactgroupcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='contextcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='hourbasketcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='hourcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='productfilter',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='productsinbasketcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='producttypefilter',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='basketcampaigntranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='campaigns.BasketCampaign'),
        ),
        migrations.AlterField(
            model_name='catalogcampaigntranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='campaigns.CatalogCampaign'),
        ),
        migrations.AlterField(
            model_name='childrenproductcondition',
            name='product',
            field=models.ForeignKey(limit_choices_to={'mode__in': [shuup.core.models.ProductMode(2), shuup.core.models.ProductMode(3)]}, null=True, on_delete=django.db.models.deletion.PROTECT, to='shuup.Product'),
        ),
    ]
