# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-25 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import jsonfield.fields
import shuup.core.fields
import shuup.notify.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', enumfields.fields.EnumIntegerField(default=1, enum=shuup.notify.enums.RecipientType, verbose_name='recipient type')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('message', models.CharField(default='', editable=False, max_length=140, verbose_name='message')),
                ('identifier', shuup.core.fields.InternalIdentifierField(blank=True, editable=False, max_length=64, null=True, unique=False)),
                ('priority', enumfields.fields.EnumIntegerField(db_index=True, default=2, enum=shuup.notify.enums.Priority, verbose_name='priority')),
                ('_data', jsonfield.fields.JSONField(blank=True, db_column='data', editable=False, null=True)),
                ('marked_read', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='marked read')),
                ('marked_read_on', models.DateTimeField(blank=True, null=True, verbose_name='marked read on')),
                ('marked_read_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='marked read by')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_identifier', models.CharField(db_index=True, max_length=64, verbose_name='event identifier')),
                ('identifier', shuup.core.fields.InternalIdentifierField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('enabled', models.BooleanField(db_index=True, default=False, verbose_name='enabled')),
                ('_step_data', jsonfield.fields.JSONField(db_column='step_data', default=[])),
                ('template', models.CharField(blank=True, default=None, help_text='the template identifier used to create this script', max_length=64, null=True, verbose_name='template identifier')),
            ],
        ),
    ]
