# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-14 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_notify', '0002_notify_script_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='template',
            field=models.CharField(blank=True, default=None, help_text='the template identifier used to create this script', max_length=64, null=True, verbose_name='template identifier'),
        ),
    ]
