# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-19 21:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0040_order_created_index'),
        ('shuup_notify', '0001_squashed_0003_alter_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shuup.Shop', verbose_name='shop'),
        ),
        migrations.AddField(
            model_name='script',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shuup.Shop', verbose_name='shop'),
        ),
    ]
