# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_notify', '0007_add-script-log-entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('template', models.TextField(help_text='Enter the base HTML template to be used in emails. Mark the place to inject the email content using the variable `%html_body%` inside the body.', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
            },
        ),
    ]
